# Generated by Django 5.0.3 on 2024-04-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
