# Generated by Django 5.0.3 on 2024-03-30 18:15

import courses.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('advantages', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=200)),
                ('includes', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(default='trashhold.png', unique=True, upload_to=courses.models.course_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
