# Generated by Django 5.0.3 on 2024-04-02 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_category_options_course_courses_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courses_access',
            field=models.ManyToManyField(related_name='courses_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
