# Generated by Django 5.0.3 on 2024-04-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_courses_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courses_access',
        ),
    ]
