# Generated by Django 5.0.3 on 2024-04-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_category_options'),
        ('courses', '0007_remove_course_courses_access'),
    ]

    operations = [
    ]
