# Generated by Django 5.0.3 on 2024-04-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20240403_1914'),
        ('courses', '0008_merge_20240403_2145'),
    ]

    operations = [
    ]
