# Generated by Django 5.0.3 on 2024-04-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lessoncontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
