# Generated by Django 5.0.3 on 2024-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lessoncontent_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='placeholder',
            field=models.CharField(default='', max_length=200),
        ),
    ]
