# Generated by Django 5.0.3 on 2024-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
