# Generated by Django 5.0.3 on 2024-04-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lessoncontent_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='watched',
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('lesson_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessoncontent')),
            ],
        ),
    ]
