# Generated by Django 5.0.3 on 2024-04-15 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lessoncontent_watched_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.lessoncontent'),
        ),
    ]
