# Generated by Django 5.0.3 on 2024-04-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
