# Generated by Django 5.0.3 on 2024-04-01 16:37

import django.db.models.deletion
import django.utils.timezone
import webinars.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=200)),
                ('includes', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(default='trashhold.png', unique=True, upload_to=webinars.models.webinar_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webinars.category')),
            ],
        ),
    ]
