# Generated by Django 5.0.3 on 2024-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
