# Generated by Django 5.0.3 on 2024-04-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_alter_webinar_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
