# Generated by Django 5.0.3 on 2024-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='price',
        ),
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.CharField(max_length=580),
        ),
    ]
