# Generated by Django 5.0.3 on 2024-04-04 20:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_remove_webinar_price_alter_webinar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(30.0)])),
                ('video_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinarlessons', to='webinars.webinar')),
            ],
        ),
    ]
