# Generated by Django 5.0.3 on 2024-04-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_webinarlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarlesson',
            name='lesson_description',
            field=models.CharField(default='No description available', max_length=1000),
        ),
    ]
